require 'oauth'
require 'oauth/signature/plaintext'
require 'json'

require 'xing_api/response_handler'
require 'xing_api/client'
require 'xing_api/base'
require 'xing_api/error'

require 'xing_api/activity'
require 'xing_api/activity/comment'
require 'xing_api/activity/like'
require 'xing_api/bookmark'
require 'xing_api/contact'
require 'xing_api/contact/tag'
require 'xing_api/contact_request'
require 'xing_api/conversation'
require 'xing_api/conversation/attachment'
require 'xing_api/conversation/message'
require 'xing_api/group'
require 'xing_api/group/forum'
require 'xing_api/group/forum/post'
require 'xing_api/group/media_preview'
require 'xing_api/group/post'
require 'xing_api/group/post/comment'
require 'xing_api/group/post/comment/like'
require 'xing_api/group/post/like'
require 'xing_api/invite'
require 'xing_api/job'
require 'xing_api/profile_message'
require 'xing_api/profile_visit'
require 'xing_api/user'
require 'xing_api/user/birth_date'
require 'xing_api/user/business_address'
require 'xing_api/user/company'
require 'xing_api/user/language'
require 'xing_api/user/photo'
require 'xing_api/user/private_address'
require 'xing_api/user/qualification'
require 'xing_api/user/recommendation'
require 'xing_api/user/school'
require 'xing_api/user/web_profile'

module XingApi
end
